### ISSUE TITLE
增加一种新的弹出样式

### ISSUE THREAD

**Issue by ghost** [Mr-VincentW/PhotoShow#36]
我写了一种弹出窗体的样式，增加了圆角之类的，感觉非常好看！
希望可以加到官方选项里面。
这样写的阴影效果可以在黑色和白色的背景都能清晰看到
```css
#photoShowViewer{
    border-radius: 10px;
    margin: 3px;
    border: 1px solid black;
}
.photoshow-viewer-shadow{
    display: none;
}
.photoshow-img-wrapper{
    border-radius: 10px;
    box-shadow: 0 0 20px #fff6, 0 0 20px #82828278, 0 0 20px #150202;
}

```

![Snipaste_2021-12-09_18-33-48](https://user-images.githubusercontent.com/49443405/145380457-c970e6c7-af69-4476-ab52-c044915edc85.png)
